---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ printf "%s-claim" (include "elastic.fullname" .) }}
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
