---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "elastic.fullname" . }}
  labels:
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
    kubernetes.io/name: "Elasticsearch"
    app: efk
    component: elastic
    release: {{ .Release.Name }}
spec:
  ports:
  - port: {{ .Values.service.dbInternalPort }}
    protocol: TCP
    targetPort: db
  selector:
    app: efk
    component: elastic
    release: {{ .Release.Name }}
