---
apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: {{ template "elastic.fullname" . }}
  labels:
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
    app: efk
    component: elastic
    release: {{ .Release.Name }}
spec:
  serviceName: {{ template "elastic.fullname" . }}
  replicas: 1
  selector:
    matchLabels:
      app: efk
      component: elastic
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: efk
        component: elastic
        release: {{ .Release.Name }}
        kubernetes.io/cluster-service: "true"
    spec:
      nodeSelector:
        elastichost: "true"
      containers:
      - image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
        name: {{ template "elastic.fullname" . }}
        resources:
          # need more cpu upon initialization, therefore burstable class
          limits:
            cpu: 1000m
          requests:
            cpu: 100m
        ports:
        - containerPort: {{ .Values.service.dbInternalPort }}
          name: db
          protocol: TCP
        - containerPort: {{ .Values.service.transportInternalPort }}
          name: transport
          protocol: TCP
        volumeMounts:
        - name: {{ printf "%s-pvc-volume" (include "elastic.fullname" .) }}
          mountPath: /data
        env:
        - name: ELASTICSEARCH_SERVICE_NAME
          value: {{ template "elastic.fullname" . }}
        - name: MINIMUM_MASTER_NODES
          value: "1"
        - name: "NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
      volumes:
      - name: {{ printf "%s-pvc-volume" (include "elastic.fullname" .) }}
        persistentVolumeClaim:
          claimName: {{ printf "%s-claim" (include "elastic.fullname" .) }}
      # Elasticsearch requires vm.max_map_count to be at least 262144.
      # If your OS already sets up this number to a higher value, feel free
      # to remove this init container.
      initContainers:
      - image: alpine:3.6
        command: ["/sbin/sysctl", "-w", "vm.max_map_count=262144"]
        name: {{ printf "%s-init" (include "elastic.fullname" .) }}
        securityContext:
          privileged: true
