global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#sergey_karakulanov'

- name: 'external mail notifications'
  email_configs:
    - to: sergey.k@gmail.com
      from: alert@prometheus.com
      smarthost: smtp.gmail.com:587
      auth_username: "sergey.k@gmail.com"
      auth_identity: "sergey.k@gmail.com"
      auth_password: "sekretik"
