version: "3.3"
services:

  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - comment_db
          - post_db

  ui:
    image: ${USER_NAME}/ui:latest
    ports:
      - ${DOCKER_APP_PORT}:${DOCKER_HOST_PORT}/tcp
    networks:
      - front_net

  post:
    image: ${USER_NAME}/post:latest
    networks:
      - back_net
      - front_net

  comment:
    image: ${USER_NAME}/comment:latest
    networks:
      - back_net
      - front_net

volumes:
  post_db:
networks:
  back_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "${BACK_NET_IP}"
  front_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "${FRONT_NET_IP}"
  prometheus_net:
