---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: auriga-mongo-persistentdisk
spec:
  capacity:
    storage: 25Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  gcePersistentDisk:
    fsType: "ext4"
    pdName: "auriga-mongo-persistentdisk"
