---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc-dymanic
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: storage-fast
  resources:
    requests:
      storage: 10Gi
