---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/component: post
    app.kubernetes.io/name: prometheus-post
    app.kubernetes.io/version: v0.34.0
  name: post
spec:
  endpoints:
  - targetPort: 5000  
    honorLabels: true
    path: /metrics
    scheme: http
  selector:
    matchLabels:
      app.kubernetes.io/component: post
      app.kubernetes.io/name: prometheus-post
      app.kubernetes.io/version: v0.34.0
